version: "3.3"

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./authelia:/config
    ports:
      - "9091:9091"
    restart: unless-stopped
    healthcheck:
      disable: true
